### ISSUE TITLE
White/blank window

### ISSUE THREAD

**Issue by CanadaHonk** [pykeio/vibe#1]
Hi! Thanks for the cool library. I tried using it on Windows 10 (21H2 - 19044.2006), and I just have a white/blank window:
![image](https://user-images.githubusercontent.com/19228318/193337586-4909ff82-ea3b-4434-bb4b-7f44e30dd4b4.png)

However, weirdly it shows fine (w/ acrylic) in the taskbar hover preview.

My code on init (before app ready):
```js
vibe.setup(require('electron').app);
```

My code in window setting:
```js
const w = new BrowserWindow({
    frame: true,
    center: true,
    backgroundColor: '#00000000',
    autoHideMenuBar: true
});
// ...
vibe.applyEffect(w, 'acrylic');
```

Thanks again!

**Comment by decahedron1** [comment]
Have you set both the `html` and `body` elements to `transparent` in your CSS?

```css
html, body {
    background-color: transparent !important;
}
```

**Comment by CanadaHonk** [comment]
They're set to transparent yeah.

**Comment by decahedron1** [comment]
Hmm, alright. What's your Electron version?

**Comment by HerXayah** [comment]
Discord should be 13.6.6 *atleast on WIndows*
