### ISSUE TITLE
Provide prebuilt binaries

### ISSUE THREAD

**Issue by decahedron1** [pykeio/vibe#6]
As much as I love Rust, it may be a bit inconvenient to have users download a Rust toolchain just to build `vibe`. `vibe` should provide prebuilt binaries so users don't need a Rust toolchain.

### The Discord problem

Many people use `vibe` in Discord client mods. Discord (at least on Windows) is still using 32-bit Electron, and I'm not sure how to handle this. Would `vibe` need a separate package just for Discord support, like `@pyke/vibe-discord`, or should `vibe` just always use 32-bit binaries on Windows?

**Comment by ArjixWasTaken** [comment]
The easy solution is to just release binaries for all architectures, I can't see how this is hard to figure out.
